/**
 * PAW SDK Session Configuration (Auto-Generated)
 *
 * @fileoverview Generated by pawSync.ts via SDKAdapter.
 * Do not edit manually — re-run `npx tsx .github/PAW/pawSync.ts` to regenerate.
 *
 * @module .paw/sdk-session
 * @version 1.0.0
 */

/**
 * Hook handler file paths grouped by SDK callback name.
 * Each callback invokes its handlers sequentially.
 */
export const PAW_SDK_HOOKS: Record<string, string[]> = {
  "onPostToolUse": [
    ".paw/hooks/post-tool-use.mjs"
  ],
  "onPreToolUse": [
    ".paw/hooks/pre-tool-use.mjs"
  ],
  "onSessionEnd": [
    ".paw/hooks/session-end-health.mjs",
    ".paw/hooks/session-end-memory-save.mjs",
    ".paw/hooks/session-end-missing-tests.mjs"
  ],
  "onUserPromptSubmitted": [
    ".paw/hooks/user-prompt-submitted.mjs"
  ]
};

/**
 * Create a Copilot SDK session config with PAW hooks wired in.
 * Import this in your SDK integration to get PAW enforcement.
 *
 * @example
 * ```typescript
 * import { createPawSessionConfig } from './.paw/sdk-session';
 * import { CopilotClient } from '@github/copilot-sdk';
 *
 * const client = new CopilotClient();
 * const session = await client.createSession(createPawSessionConfig());
 * ```
 *
 * @returns Partial session config with hooks callbacks
 */
export function createPawSessionConfig(): Record<string, unknown> {
  return {
    hooks: PAW_SDK_HOOKS,
    skillDirectories: [".github/skills"],
  };
}
