/**
 * PAW SDK Session Configuration (Auto-Generated)
 *
 * @fileoverview Generated by pawSync.ts via SDKAdapter.
 *
 * @module .paw/sdk-session
 * @version 1.0.0
 */

/**
 * Hook handler file paths grouped by SDK callback name.
 */
export const PAW_SDK_HOOKS: Record<string, string[]> = {
  "onPostToolUse": [
    ".paw/hooks/postToolUse.mjs"
  ],
  "onPreToolUse": [
    ".paw/hooks/preToolUse.mjs"
  ],
  "onSessionEnd": [
    ".paw/hooks/sessionEndHealth.mjs",
    ".paw/hooks/sessionEndMemorySave.mjs",
    ".paw/hooks/sessionEndMissingTests.mjs"
  ],
  "onUserPromptSubmitted": [
    ".paw/hooks/userPromptSubmitted.mjs"
  ]
};

/**
 * Create a Copilot SDK session config with PAW hooks wired in.
 *
 * @example
 * ```typescript
 * import { createPawSessionConfig } from './.paw/sdk-session';
 * import { CopilotClient } from '@github/copilot-sdk';
 *
 * const client = new CopilotClient();
 * const session = await client.createSession(createPawSessionConfig());
 * ```
 *
 * @returns Partial session config with hooks callbacks
 */
export function createPawSessionConfig(): Record<string, unknown> {
  return {
    hooks: PAW_SDK_HOOKS,
    skillDirectories: [".github/skills"],
  };
}
