/**
 * CI Mode: Minimal MDX Components Generator
 *
 * @fileoverview Generates a minimal mdxComponents.tsx file without analyzing for reusable outliers.
 * This is used in CI environments where the full analysis step is skipped.
 *
 * @module findReusableMdxOutliers.ci
 * @version 1.0.0
 * @since 1.0.0
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createLogger } from '@/lib/logging/logger';

const log = createLogger({ script: 'findReusableMdxOutliers.ci' });

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const outputPath = path.join(
  __dirname,
  '..',
  '..',
  'src',
  'lib',
  'components',
  'mdx',
  'mdxComponents.tsx',
);
const outputDir = path.dirname(outputPath);

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const minimalContent = `/**
 * @fileoverview MDX Components - Auto-generated (CI mode)
 * @description Minimal placeholder generated during CI builds.
 * In development, run: npm run find-reusable-mdx-outliers
 */

// This file is generated during CI builds and contains compiled MDX components.
// In development, this is populated by find-reusable-mdx-outliers with actual components.
// Do not edit this file manually - it will be overwritten.

export const mdxComponents = {};
`;

fs.writeFileSync(outputPath, minimalContent, 'utf-8');

log.message('✅ Generated minimal mdxComponents.tsx for CI environment', {
  path: outputPath,
});
