/**
 * CI Mode: Minimal MDX Components Generator
 * 
 * Generates a minimal mdxComponents.tsx file without analyzing for reusable outliers.
 * This is used in CI environments where the full analysis step is skipped.
 * 
 * @fileoverview Minimal version for CI pipelines
 */

const fs = require('fs');
const path = require('path');

const outputPath = path.join(__dirname, '..', '..', 'src', 'lib', 'components', 'mdx', 'mdxComponents.tsx');
const outputDir = path.dirname(outputPath);

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Create minimal mdxComponents.tsx with no exports
const minimalContent = `/**
 * @fileoverview MDX Components - Auto-generated (CI mode)
 * @description Minimal placeholder generated during CI builds.
 * In development, run: npm run find-reusable-mdx-outliers
 */

// This file is generated during CI builds and contains compiled MDX components.
// In development, this is populated by find-reusable-mdx-outliers.js with actual components.
// Do not edit this file manually - it will be overwritten.

export const mdxComponents = {};
`;

fs.writeFileSync(outputPath, minimalContent, 'utf-8');

console.log('✅ Generated minimal mdxComponents.tsx for CI environment');
console.log(`   Path: ${outputPath}`);
